### ISSUE TITLE
#1 fix page routing

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#41]
Bug occurs in these user flows:
- submission of plant in add plant form
- delete plant

Depending on where we want to go with the `add a plant` feature, this could also become irrelevant.

Right now, we should consider this as a bug.

Maybe we can fix it by making changes to the submit handler in `Form`.

**Comment by levinthiel** [comment]
Yes I think it is just a matter of auto routing, where we need to change the link and that would be it ;) 

I think after adding the plant we route to the "home" that is now the intro
